name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} \
          -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/portfolioapp:latest .

      # Step 4: Push the Docker image to ACR
      - name: Push Docker image
        run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/portfolioapp:latest

      # Step 5: Log in to Azure (required before deployment)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 6: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/portfolioapp:latest
