name: CI-CD Pipeline (DockerHub + AKS)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 3: Build and push Docker image to Docker Hub
    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/portfolio-website
        docker build -t $IMAGE_NAME:${{ github.sha }} .
        docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ github.sha }}
        docker push $IMAGE_NAME:latest

    # Step 4: Log in to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 5: Get AKS credentials
    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group portfolio-rg --name portfolio-aks --overwrite-existing

    # Step 6: Deploy to AKS
    - name: Deploy to AKS
      run: |
        kubectl set image deployment/portfolio-app portfolio=${{ secrets.DOCKERHUB_USERNAME }}/portfolio-website:latest --record
        kubectl rollout status deployment/portfolio-app
